name: flutter_stylish
description: A new Flutter project for stylish

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.7.12'

dependencies:

  flutter_webrtc: ^0.9.27

  json_annotation: ^4.8.0

  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  dio: ^5.1.1
  json_serializable: ^6.6.0
  


dev_dependencies:

  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/stylish_logo.png