name: flutter_stylish
description: A new Flutter project for stylish

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/stylish_logo.png